# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00d2eae40edb556fb0c9d8f273a8eea2f2094630b00926ca0b13a18f2cfeafa506e147b1a8d4403f882d58c966f2dace5a1c02f0aeab0492898308abeec21c06

test:
  secret_key_base: 007cf9ec3fb6a769c081cf26e0bd7cc445c0095cb38661e5ac50a999d11e5d7c9cd76b3a9c9e5b35912516ca81ea7d1e03f0111e4c1ea8cb069136bed95dd3ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
